"""Fixing user table register date

Revision ID: 34499e6fd1d4
Revises: ea5adbaee223
Create Date: 2025-01-14 23:47:44.637651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34499e6fd1d4'
down_revision: Union[str, None] = 'ea5adbaee223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
